services:
    server:
        build: ./server
        ports:
            - 5050:5000
        volumes:
            - ./server/src/:/app/src
    client:
        build: ./client
        ports:
          - 8080:80
        volumes:
            - ./client/src/:/app/src

    mongodb:
        image: mongo
        volumes:
            - ./data:/data/db